import express from "express";
import contactCtrl from "../controllers/contact.controller.js";
import authCtrl from "../controllers/auth.controller.js";
const router = express.Router();
router.route("/api/contacts").post(contactCtrl.create);
router.route("/api/contacts").get(contactCtrl.list);
router.route("/api/contacts").delete(authCtrl.requireSignin, authCtrl.requireRole("admin"), contactCtrl.removeAll);
router.param("contactId", contactCtrl.contactByID);
router.route("/api/contacts/:contactId").get(contactCtrl.read);
router.route("/api/contacts/:contactId").put(authCtrl.requireSignin, authCtrl.requireRole("admin"), contactCtrl.update);
router.route("/api/contacts/:contactId").delete(authCtrl.requireSignin, authCtrl.requireRole("admin"), contactCtrl.remove);
export default router;
